# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c360543703385083f0d54d2b722d5dce33f6433f7b303c68513ab339cf7999133a273cd6167cb6c6581365c47037736cc39cfbe786100ae6f0ea1e730bae05d4

test:
  secret_key_base: 763d5406c42f9040ccb7f6afe0dad71bb58bd7af6bd11151a6a1de1ae7bf130ea621f3278dca6a44f8f85a68db77658456c2b2c7c78957a337342a62f1db9d8a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
